import { Circle, Code2, FlaskConical, Rocket } from 'lucide-react';
import {
    SiJavascript,
    SiTypescript,
    SiPython,
    SiNodedotjs,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiAngular,
    SiGo,
    SiOpenjdk,
    SiPhp,
    SiRuby,
    SiRubyonrails,
    SiKotlin,
    SiSwift,
    SiC,
    SiCplusplus,
    SiRust,
    SiFlutter,
    SiSvelte,
    SiNuxtdotjs,
    SiNestjs,
    SiExpress,
    SiLaravel,
    SiDjango,
    SiFastapi,
    SiSpring,
  
    SiDocker,
    SiKubernetes,
    SiGooglecloud,
    SiElectron,
  
    SiVite,
    
    SiTerraform,
    SiLinux,
    SiNginx,
    SiApache,
  } from 'react-icons/si'
  
export const ICONS: Record<string, { label: string; Icon: React.ComponentType<{ className?: string }>; color: string }> = {
    javascript: { label: 'JavaScript', Icon: SiJavascript, color: '#f7df1e' },
    typescript: { label: 'TypeScript', Icon: SiTypescript, color: '#3178c6' },
    python: { label: 'Python', Icon: SiPython, color: '#3776ab' },
    node: { label: 'Node.js', Icon: SiNodedotjs, color: '#339933' },
    react: { label: 'React', Icon: SiReact, color: '#61dafb' },
    next: { label: 'Next.js', Icon: SiNextdotjs, color: '#ffffff' },
    vue: { label: 'Vue', Icon: SiVuedotjs, color: '#42b883' },
    angular: { label: 'Angular', Icon: SiAngular, color: '#c3002f' },
    go: { label: 'Go', Icon: SiGo, color: '#00ADD8' },
    java: { label: 'Java', Icon: SiOpenjdk, color: '#5382a1' },
    php: { label: 'PHP', Icon: SiPhp, color: '#777bb4' },
    ruby: { label: 'Ruby', Icon: SiRuby, color: '#cc342d' },
    rails: { label: 'Ruby on Rails', Icon: SiRubyonrails, color: '#cc0000' },
    kotlin: { label: 'Kotlin', Icon: SiKotlin, color: '#0095d5' },
    swift: { label: 'Swift', Icon: SiSwift, color: '#fa7343' },
    c: { label: 'C', Icon: SiC, color: '#a8b9cc' },
    cpp: { label: 'C++', Icon: SiCplusplus, color: '#00599c' },
    rust: { label: 'Rust', Icon: SiRust, color: '#dea584' },
    flutter: { label: 'Flutter', Icon: SiFlutter, color: '#02569b' },
    svelte: { label: 'Svelte', Icon: SiSvelte, color: '#ff3e00' },
    nuxt: { label: 'Nuxt.js', Icon: SiNuxtdotjs, color: '#00C58E' },
    nest: { label: 'NestJS', Icon: SiNestjs, color: '#e0234e' },
    express: { label: 'Express', Icon: SiExpress, color: '#aaaaaa' },
    laravel: { label: 'Laravel', Icon: SiLaravel, color: '#ff2d20' },
    django: { label: 'Django', Icon: SiDjango, color: '#092e20' },
    fastapi: { label: 'FastAPI', Icon: SiFastapi, color: '#009688' },
    spring: { label: 'Spring', Icon: SiSpring, color: '#6db33f' },
    docker: { label: 'Docker', Icon: SiDocker, color: '#2496ed' },
    kubernetes: { label: 'Kubernetes', Icon: SiKubernetes, color: '#326ce5' },
    gcp: { label: 'Google Cloud', Icon: SiGooglecloud, color: '#4285f4' },
    electron: { label: 'Electron', Icon: SiElectron, color: '#47848f' },
    vite: { label: 'Vite', Icon: SiVite, color: '#646cff' },
    terraform: { label: 'Terraform', Icon: SiTerraform, color: '#7b42bc' },
    linux: { label: 'Linux', Icon: SiLinux, color: '#fcc624' },
    nginx: { label: 'Nginx', Icon: SiNginx, color: '#009639' },
    apache: { label: 'Apache', Icon: SiApache, color: '#d22128' },
  }
export const iconOptions: Array<{ value: string; label: string }> = Object.entries(ICONS).map(([value, meta]) => ({ value, label: meta.label }))


export const ENVIRONMENTS: Record<string, { label: string; color: string; Icon: React.ComponentType<{ className?: string }> }> = {
  default: { label: 'Default', color: '#9ca3af', Icon: Circle },
  development: { label: 'Development', color: '#22c55e', Icon: Code2 },
  staging: { label: 'Staging', color: '#f59e0b', Icon: FlaskConical },
  production: { label: 'Production', color: '#ef4444', Icon: Rocket },
}